### PR TITLE
Discord Considered Harmful

### PR DESCRIPTION
**Pull request by SnowyJune678**
Haha funny goto considered harmful
Replaced Valour promotion with YT video explaining the situation

### CODE REVIEW

**Review by identithree — CHANGES_REQUESTED** [review]
But its funnier

**Comment by Coca162** [comment]
Idk man bad isn't that funni

**Comment by identithree** [comment]
yea but like, it funny because discord bad. i am not lying

**Review by Coca162 — APPROVED** [review]
> yea but like, it funny because discord bad. i am not lying

pretty flat joke i think this is better ngl

**Comment by identithree** [comment]
your brain is a flat joke /s

**Comment by Coca162** [comment]
Just for that, I am merging this

**Pull request merged**
